#!/bin/bash
alias code='/usr/share/code/code --no-sandbox --user-data-dir=.vscode'
cd ~
export DONT_PROMPT_WSL_INSTALL=1
export LANG=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
export LC_LANG=zh_CN.UTF-8

export LIBGL_ALWAYS_INDIRECT=
export GDK_THEME=
export XDG_SESSION_TYPE="x11"
#export GDK_SCALE=2
#export GDK_DPI_SCALE=1
#export ELM_SCALE=2
#export QT_SCALE_FACTOR=1
#export QT_FONT_DPI=144
#export QT_STYLE_OVERRIDE=adwaita
export QT_QPA_PLATFORMTHEME=gtk2
export DESKTOP_SESSION=gnome

#GDK_SYNCHRONIZE
#GDK_CORE_DEVICE_EVENTS

#GTK_PATH
#GDK_DEBUG
#GTK_EXE_PREFIX
#GTK_DATA_PREFIX
#export GTK_THEME=Adwaita-dark
#export GTK_CURSOR_SIZE=48
#export GTK_THEME=Greybird-dark
#export HOSTIP=`nslookup w541|sed -n "1, 1p"|awk '{print $2}'`
export HOSTIP=$(ip route | awk '/^default/{print $3; exit}')
export DISPLAY=$HOSTIP:0.0
export PULSE_SERVER=tcp:$HOSTIP

#DESKTOP_STARTUP_ID
#XDG_DATA_HOME
#XDG_DATA_DIRS
#GTK_OVERLAY_SCROLLING
#GTK_CSD
#GDK_BACKEND
#GDK_RENDERING
#GDK_PIXBUF_MODULE_FILE
#export GTK_IM_MODULE=ibus
#export GTK_IM_MODULE_FILE
#export XMODIFIERS=@im=ibus
#export QT_IM_MODULE=ibus
#export XIM_PROGRAM="ibus-daemon"
export NO_AT_BRIDGE=1
export LC_CTYPE=zh_CN.UTF-8
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
/usr/bin/wslfcitx

/usr/bin/startXServer
export PATH=/opt/dart-sdk/bin:/opt/flutter/bin:$PATH



alias reboot='sudo /usr/bin/reboot'
