#!/bin/bash
PROC_NAME=sshd
ProcNumber=`ps -ef |grep -w $PROC_NAME|grep -v grep|wc -l`
#echo $ProcNumber
if [ $ProcNumber -le 0 ];then
        echo "--->run sshd<---"
        export localhost_ip=`ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d addr:`
        echo $localhost_ip
#        /mnt/c/WINDOWS/System32/cmd.exe /c "netsh interface portproxy add v4tov4 listenport=22 listenaddress=0.0.0.0 connectport=22 connectaddress=$localhost_ip" > /dev/null 2>&1 &
        /usr/bin/mkdir /run/sshd > /dev/null 2>&1
        /usr/sbin/sshd -D
        #-D > /dev/null 2>&1 &
fi
export localhost_ip=`ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d addr:`
/mnt/c/WINDOWS/System32/cmd.exe /c "netsh interface portproxy add v4tov4 listenport=22 listenaddress=0.0.0.0 connectport=22 connectaddress=$localhost_ip" > /dev/null 2>&1 &
